### ISSUE TITLE
monitord Failing

### ISSUE THREAD

**Issue by spficklin** [feltus/OSG-GEM#4]
I'm getting the following error message in the monitord log files when running OSG-GEM.  The workflow doesn't seem to work for me :-/  ... so, I'm digging into it.  This may not be related bu thought I'd point out. 

cat monitord.log

Traceback (most recent call last):
  File "/home/rynge/software/pegasus-4.7.0dev/bin/pegasus-monitord", line 56, in <module>
    from Pegasus.monitoring.workflow import Workflow, MONITORD_RECOVER_FILE
  File "/home/rynge/software/pegasus-4.7.0dev/lib64/python2.6/site-packages/Pegasus/monitoring/workflow.py", line 78, in <module>
    class Workflow:
  File "/home/rynge/software/pegasus-4.7.0dev/lib64/python2.6/site-packages/Pegasus/monitoring/workflow.py", line 99, in Workflow
    CONDOR_VERSION_8_3_3 = get_numeric_version.__func__( 8,3,3 )
AttributeError: 'staticmethod' object has no attribute '__func__'

**Comment by wpoehlm** [comment]
I hadn't noticed that, but I'm getting the same message from successfully completed workflows.  This might affect re-submitting failed workflows, so we'll look into it.

**Comment by rynge** [comment]
I saw this message and well, and I think it has been fixed in Pegasus now.
